# Generated by Django 3.2.6 on 2023-12-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='value',
            field=models.TextField(max_length=100, null=True, unique=True),
        ),
    ]
